project:
  type: book

book:
  title: "iLand - the book"
  author: "iLand Team"
  date: "30.10.2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: Part_I.qmd
      chapters:
       - Working_with_iLand.qmd
       - iLand_inputs.qmd
       - include_script_report.qmd
    - part: Part_II.qmd
      chapters:
      - Scripting.qmd
      - Using_ABE.qmd
      - Setting_up_landscapes.qmd
      - Calibration_evaluation.qmd
      - Species_parameterization.qmd
      - Managing_simulation_experiments.qmd
      - Building_iLand.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

