project:
  type: book

book:
  title: "iLand - the book"
  author: "iLand Team"
  date: "30.10.2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part I - Getting to know iLand"
      chapters:
       - Working with iLand.qmd
       - 4_iLandInputs.qmd
    - part: "Part II - Digging deeper"
      chapters:
      - scripting.qmd
      - UsingAbe.qmd
      - 2_8_SettingUpLandscapes.qmd
      - 10_Calibration_Evaluation.qmd
      - Species_parameterization.qmd
      - 11_ManagingSimulationExperiments.qmd
      - Building iLand.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

