project:
  type: book

author: iLand Team
book:
  chapters:
    - file: index.qmd
    - file: preface.qmd
    - intro.qmd
    - part: Part_I.qmd
      chapters:
        - IngredientsiLandProject.qmd
        - iLandGUI.qmd
        - include_script_report.qmd
    - part: Part_II.qmd
      chapters:
      - Scripting.qmd
      - Using_ABE.qmd
      - Setting_up_landscapes.qmd
      - Species_parameterization.qmd
      - Calibration_evaluation.qmd
      - Managing_simulation_experiments.qmd
      - Building_iLand.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    title: iLand - the book
    author: iLand Team
    date: today
    header-includes: \titlehead{\includegraphics[width=1\linewidth]{"images/iland-cover-image.png"}}

editor: visual

